#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication fluentMeshToFoam AMI.msh

runApplication topoSet

decomposePar

pyFoamPlotRunner.py mpirun -np 6 polymSimpleFoam -parallel
 
echo "Done!"
#------------------------------------------------------------------------------
