#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf PyFoam*
rm -rf Gnuplotting.analyzed
rm -rf continuity*
rm -rf linear*
rm nonMRF.foam

echo "Done!"
#------------------------------------------------------------------------------
