#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

foamMonitor -l -r 1 postProcessing/residual1/0/residuals.dat

echo "Erledigt!"
#------------------------------------------------------------------------------
